# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 07:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_updators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MillitaryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spouse', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=datetime.datetime(2018, 4, 15, 7, 2, 52, 220275, tzinfo=utc))),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('social_security_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('home_phone', models.CharField(max_length=16)),
                ('cell_phone', models.CharField(max_length=16)),
                ('fax', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('authorization_to_work_in_the_us', models.CharField(choices=[('us citizen', 'US Citizen'), ('permanent alien', 'Permanent Alien'), ('temporary alien', 'Temporary Alien'), ('refugee', 'Refugee')], max_length=50)),
                ('are_you_registered_in_JobGateway', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('how_did_you_hear_about_us', models.CharField(max_length=20)),
                ('CareerLink_program', multiselectfield.db.fields.MultiSelectField(choices=[('JobGateway\xae Registration', 'JobGateway\xae Registration'), ('UC \u2013 Filing for Benefits or Appeals', 'UC \u2013 Filing for Benefits or Appeals'), ('Veterans Services', 'Veterans Services'), ('Calendar of Events', 'Calendar of Events'), ('Labor Market Information', 'Labor Market Information'), ('Resume Assistance', 'Resume Assistance'), ('Job Search Planning/Career Counseling', 'Job Search Planning/Career Counseling'), ('Networking', 'Networking'), ('Interviewing', 'Interviewing'), ('Identifying Skills', 'Identifying Skills'), ('Civil Service/Government Jobs', 'Civil Service/Government Jobs'), ('Job Search Websites', 'Job Search Websites'), ('Supportive Services Information', 'Supportive Services Information'), ('Disability Resources', 'Disability Resources'), ('Tracking My Job Search', 'Tracking My Job Search'), ('Job Search Basics/Show Me the Jobs', 'Job Search Basics/Show Me the Jobs'), ('Starting a Business', 'Starting a Business'), ('Basic Computer Skills (Mouse, Keyboard, etc.)', 'Basic Computer Skills (Mouse, Keyboard, etc.)'), ('Computer Skills (MS Word, Outlook, etc.)', 'Computer Skills (MS Word, Outlook, etc.)'), ('Re\u2010Entry Resources', 'Re\u2010Entry Resources'), ('English as a Second Language (ESL)', 'English as a Second Language (ESL)'), ('Basic Reading/Writing/Math Skills', 'Basic Reading/Writing/Math Skills'), ('Obtaining an Occupational Certification or License', 'Obtaining an Occupational Certification or License'), ('Obtaining Your High School Equivalency Diploma', 'Obtaining Your High School Equivalency Diploma')], default=None, max_length=675)),
                ('education', models.CharField(max_length=20)),
                ('Most_Recent_Employer', models.CharField(blank=True, max_length=20)),
                ('Most_Recent_Job_Title', models.CharField(blank=True, max_length=20)),
                ('Most_Recent_Job_Start_Date', models.DateField(blank=True, null=True)),
                ('Most_Recent_Job_End_Date', models.DateField(blank=True, null=True)),
                ('Wage_per_Hour', models.CharField(blank=True, max_length=50)),
                ('Hours_Per_Week', models.CharField(blank=True, max_length=50)),
                ('is_Hispanic', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('Race', models.CharField(choices=[('American Indian/Alaskan Native', 'American Indian/Alaskan Native'), ('Asian', 'Asian'), ('Black/African American', 'Black/African American'), ('Hawaiian Native/other Pacific Islander', 'Hawaiian Native/other Pacific Islander'), ('White', 'White'), ('Do not Wish to Disclose', 'Do not Wish to Disclose')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JobGateway\xae Registration', 'JobGateway\xae Registration'), ('UC \u2013 Filing for Benefits or Appeals', 'UC \u2013 Filing for Benefits or Appeals'), ('Veterans Services', 'Veterans Services'), ('Calendar of Events', 'Calendar of Events'), ('Labor Market Information', 'Labor Market Information'), ('Resume Assistance', 'Resume Assistance'), ('Job Search Planning/Career Counseling', 'Job Search Planning/Career Counseling'), ('Networking', 'Networking'), ('Interviewing', 'Interviewing'), ('Identifying Skills', 'Identifying Skills'), ('Civil Service/Government Jobs', 'Civil Service/Government Jobs'), ('Job Search Websites', 'Job Search Websites'), ('Supportive Services Information', 'Supportive Services Information'), ('Disability Resources', 'Disability Resources'), ('Tracking My Job Search', 'Tracking My Job Search'), ('Job Search Basics/Show Me the Jobs', 'Job Search Basics/Show Me the Jobs'), ('Starting a Business', 'Starting a Business'), ('Basic Computer Skills (Mouse, Keyboard, etc.)', 'Basic Computer Skills (Mouse, Keyboard, etc.)'), ('Computer Skills (MS Word, Outlook, etc.)', 'Computer Skills (MS Word, Outlook, etc.)'), ('Re\u2010Entry Resources', 'Re\u2010Entry Resources'), ('English as a Second Language (ESL)', 'English as a Second Language (ESL)'), ('Basic Reading/Writing/Math Skills', 'Basic Reading/Writing/Math Skills'), ('Obtaining an Occupational Certification or License', 'Obtaining an Occupational Certification or License'), ('Obtaining Your High School Equivalency Diploma', 'Obtaining Your High School Equivalency Diploma')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VeteransInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_millitary_service', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('Service_relative_disability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('VA_Compensation', models.CharField(blank=True, max_length=3)),
                ('Entry_Date', models.DateField(blank=True)),
                ('Separation_Date', models.DateField(blank=True)),
                ('Type_of_Discharge', models.CharField(blank=True, choices=[('Honorable', 'Honorable'), ('Dishonorable', 'Dishonorable'), ('Other', 'Other')], max_length=50)),
                ('Milliatary_Badge', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('Your_Branch_of_Service', models.CharField(blank=True, choices=[('Army', 'Army'), ('Army Reserves', 'Army Reserves'), ('Navy', 'Navy'), ('Navy Reserves', 'Navy Reserves'), ('Air Force', 'Air Force'), ('Air Force Reserves', 'Air Force Reserves'), ('Marines', 'Marines'), ('Marine Reserves', 'Marine Reserves'), ('Coast Guard', 'Coast Guard'), ('Coast Guard Reserves', 'Coast Guard Reserves'), ('National Guard', 'National Guard')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='PersonalInformations', to='CareerLink.Profile', unique=True),
        ),
    ]
